import{i as c,S as d}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const l=document.querySelector(".loader");function u(){l.style.display="block"}function i(){l.style.display="none"}async function f(n){const s=`https://pixabay.com/api/?key=44758497-ea11318ae0823ef09cb8fbdb5&q=${encodeURIComponent(n)}&image_type=photo`;try{u();const o=await fetch(s);if(!o.ok)throw new Error("Не вдалося виконати запит.");const e=await o.json();return i(),e.totalHits>0?(c.show({position:"topRight",backgroundColor:"green",message:`Found ${e.totalHits} results.`}),e.hits):(c.show({position:"topRight",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),[])}catch(o){throw i(),console.error("Помилка під час виконання запиту:",o),o}}function m(n){const t=document.querySelector("#gallery");if(!t){console.error("Елемент #gallery не знайдений в DOM.");return}if(n.length===0){t.innerHTML="<p>Нічого не знайдено.</p>";return}const s=n.map(o=>`
      <div class="image-card">
            <a href="${o.largeImageURL}"><img src="${o.webformatURL}" alt="${o.tags}" /></a>
            <div class="image-text">
        <p>views: ${o.views}</p>
        <p>comments: ${o.comments}</p>
        <p>downloads: ${o.downloads}</p>
        </div>
      </div>
    `).join("");t.innerHTML=s,new d(".image-card a",{captionsData:"alt",captionDelay:250,navText:["&larr;","&rarr;"],closeText:"&times;"})}document.addEventListener("DOMContentLoaded",()=>{console.log("DOM повністю завантажений і готовий.");const n=document.querySelector("#search-form");if(!n){console.error("Форма не знайдена.");return}n.addEventListener("submit",t=>{t.preventDefault(),console.log("Обробка події submit.");const o=new FormData(t.target).get("query");o&&o.trim()?(console.log("Форма відправлена з даними:"),console.log(`Пошуковий запит: ${o.trim()}`),f(o.trim()).then(e=>m(e)).catch(e=>console.log(e))):(console.log("Поле вводу пусте."),alert("Будь ласка, введіть пошуковий запит."))})});
//# sourceMappingURL=commonHelpers.js.map
