import{i,S as d}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const l=document.querySelector(".loader");function u(){l.style.display="block"}function c(){l.style.display="none"}async function f(s){const n=`https://pixabay.com/api/?key=44758497-ea11318ae0823ef09cb8fbdb5&q=${encodeURIComponent(s)}&image_type=photo`;try{u();const t=await fetch(n);if(!t.ok)throw new Error("Не вдалося виконати запит.");const e=await t.json();return c(),e.totalHits>0?(i.show({position:"topRight",backgroundColor:"green",message:`Found ${e.totalHits} results.`}),e.hits):(i.show({position:"topRight",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),[])}catch(t){throw c(),t}}function p(s){const r=document.querySelector("#gallery");if(!r){console.error("Елемент #gallery не знайдений в DOM.");return}if(s.length===0){r.innerHTML="<p>Нічого не знайдено.</p>";return}const n=s.map(t=>`
      <div class="image-card">
            <a href="${t.largeImageURL}"><img src="${t.webformatURL}" alt="${t.tags}" /></a>
            <div class="image-text">
        <p>likes: ${t.likes}</p>
        <p>views: ${t.views}</p>
        <p>comments: ${t.comments}</p>
        <p>downloads: ${t.downloads}</p>
        </div>
      </div>
    `).join("");r.innerHTML=n,m.refresh()}const m=new d(".image-card a",{captionsData:"alt",captionDelay:250,navText:["&larr;","&rarr;"],closeText:"&times;"});document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector("#search-form");if(!s){console.error("Форма не знайдена.");return}s.addEventListener("submit",r=>{r.preventDefault();const t=new FormData(r.target).get("query");t&&t.trim()?(console.log(`Пошуковий запит: ${t.trim()}`),f(t.trim()).then(e=>p(e)).catch(e=>console.log(e))):alert("Будь ласка, введіть пошуковий запит.")})});
//# sourceMappingURL=commonHelpers.js.map
