import{S as u,i}from"./assets/vendor-8c59ed88.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const l=document.querySelector(".loader");function d(){l.style.display="block"}function f(){l.style.display="none"}function p(s){const r=`https://pixabay.com/api/?key=44758497-ea11318ae0823ef09cb8fbdb5&q=${encodeURIComponent(s)}&image_type=photo`;return fetch(r).then(t=>{if(!t.ok)throw new Error("Не вдалося виконати запит.");return t.json()})}const m=document.querySelector("#gallery");function h(s){const n=s.map(r=>`
      <div class="image-card">
            <a href="${r.largeImageURL}"><img src="${r.webformatURL}" alt="${r.tags}" /></a>
            <div class="image-text">
        <p>likes: ${r.likes}</p>
        <p>views: ${r.views}</p>
        <p>comments: ${r.comments}</p>
        <p>downloads: ${r.downloads}</p>
        </div>
      </div>
    `).join("");m.innerHTML=n,g.refresh()}const g=new u(".image-card a",{captionsData:"alt",captionDelay:250,navText:["&larr;","&rarr;"],closeText:"&times;"}),c=document.querySelector("#search-form");c.addEventListener("submit",s=>{s.preventDefault();const r=new FormData(s.target).get("query");if(!r.trim())return i.show({position:"center",backgroundColor:"orange",message:"Будь ласка, введіть пошуковий запит."});d(),p(r.trim()).then(t=>{if(t.hits.length===0)return i.show({position:"topRight",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"});i.show({position:"topRight",backgroundColor:"green",message:`Found ${t.totalHits} results.`}),console.log(t.hits),h(t.hits),c.reset()}).catch(t=>{i.show({position:"topRight",backgroundColor:"red",message:"Error during the request. Please try again later."})}).finally(()=>f())});
//# sourceMappingURL=commonHelpers.js.map
